language: python
python: 2.7
sudo: false
services: redis-server
addons:
  postgresql: "9.3"
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
    - TOX_ENV=docs
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
