language: python
python: 2.7
sudo: true
services: redis-server
addons:
  postgresql: "9.3"
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
    - TOX_ENV=docs
before_install:
    - sudo apt-get install postgresql-contrib-9.3
    - git clone https://github.com/mozilla-services/kinto.git kinto
    - pushd kinto
    - make install-dev
    - .venv/bin/pserve ../cliquet/tests/config/kinto.ini&
    - popd
install:
    - pip install tox
before_script:
    - psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres ; psql -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
script:
    - tox -e $TOX_ENV
