language: python
python: 2.7
sudo: true
services: redis-server
addons:
  postgresql: "9.4"
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
    - TOX_ENV=docs
before_install:
    # <Kinto>
    # Use this cliquet.
    - pip install -e ".[postgresql,monitoring]"
    - git clone https://github.com/mozilla-services/kinto.git kinto
    - pushd kinto
    - make install-dev
    - popd
    # Run in background.
    - make runkinto &
    # </Kinto>
install:
    - pip install tox
before_script:
    - psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
