language: python
python: 2.7
services: redis-server
addons:
  postgresql: "9.4"
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=py27-raw
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - ACTION=loadtest_simulation
matrix:
  allow_failures:
    - env: ACTION=loadtest_simulation

install:
    - pip install tox
before_script:
    - sudo sed -i "s/fsync/#fsync/" /etc/postgresql/9.4/main/postgresql.conf
    - sudo /etc/init.d/postgresql restart
    - psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres
script:
    - if [[ $ACTION != loadtest_simulation ]]; then tox -e $TOX_ENV; fi
    - if [[ $ACTION == loadtest_simulation ]]; then make loadtest-check-simulation; fi
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
