db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
web:
  build: .
  links:
   - db
  ports:
   - "8888:8888"
  environment:
    CLIQUET_CACHE_BACKEND: cliquet.cache.postgresql
    CLIQUET_CACHE_URL: postgres://postgres:postgres@db/postgres
    CLIQUET_STORAGE_BACKEND: cliquet.storage.postgresql
    CLIQUET_STORAGE_URL: postgres://postgres:postgres@db/postgres
    CLIQUET_PERMISSION_BACKEND: cliquet.permission.postgresql
    CLIQUET_PERMISSION_URL: postgres://postgres:postgres@db/postgres
